### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by BonkaBonka** [iancmcc/greenlight#1]
bonka@newbuntu:~/venv$ bin/pip install greenlight
Downloading/unpacking greenlight
  Downloading greenlight-0.1.tar.gz
  Running setup.py egg_info for package greenlight
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/bonka/venv/build/greenlight/setup.py", line 5, in <module>
        with open(os.path.join(os.path.dirname(**file**), 'README.rst')) as f:
    IOError: [Errno 2] No such file or directory: '/home/bonka/venv/build/greenlight/README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/bonka/venv/build/greenlight/setup.py", line 5, in <module>

```
with open(os.path.join(os.path.dirname(__file__), 'README.rst')) as f:
```

IOError: [Errno 2] No such file or directory: '/home/bonka/venv/build/greenlight/README.rst'

---

Command python setup.py egg_info failed with error code 1 in /home/bonka/venv/build/greenlight
Storing complete log in /home/bonka/.pip/pip.log

**Comment by traviskaufman** [comment]
We fixed this on [our fork](https://github.com/refinery29/greenlight)
